# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{app_constants}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kris Kowalik", "Leonardo Borges"]
  s.date = %q{2010-03-25}
  s.description = %q{AppConstants is a very simple plugin that provides a clean way to handle this need.}
  s.email = %q{leonardoborges.rj@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "lib/app_constants.rb",
     "lib/generators/USAGE",
     "lib/generators/app_constants_generator.rb",
     "lib/generators/templates/constants.yml",
     "lib/generators/templates/load_app_constants.rb",
     "tasks/app_constants_tasks.rake",
     "test/app_constants_test.rb",
     "test/fixtures/constants.yml",
     "test/fixtures/nested_constants.yml",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/kriss/app_constants}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A clean and simple way to manage your application's per-environment constants}
  s.test_files = [
    "test/app_constants_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

